### ISSUE TITLE
unit-java depends on deprecated java

### ISSUE THREAD

**Issue by mfirry** [nginx/homebrew-unit#1]
I get this error:

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/nginx/homebrew-unit/Formula/unit-java.rb
unit-java: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the nginx/unit tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/nginx/homebrew-unit/Formula/unit-java.rb:8
```

**Comment by mar0x** [comment]
Hello,
This [commit](https://github.com/Homebrew/brew/commit/74fb058c7ed6b382ec92160d4d57f5459d4b8e2d#diff-0be9d449c0537e491b1c872019711b8b63c72dc2de14963b20797b61bab25b49R37) suddenly makes using `depends_on :java` deprecated. Depending on `openjdk` is not the same thing, because it is installed _keg only_ to avoid collision with system java, depending on which is deprecated :)
For now, the quick fix is removing or commenting out the line `depends_on :java`.

**Comment by mar0x** [comment]
Dependency removed at 0711705.
